// frontend/src/pages/Login.jsx
import { useState } from "react"

const Login = () => {

    const [state, setState] = useState('Sign Up')
    const [email, setEmail] = useState('')
    const [password, setPassword] = useState('')
    const [name, setName] = useState('')

    const onSubmitHandler = async (event) => {
        event.preventDefault()
    }

    return (
        <form className="min-h-[80vh] flex items-center">
            <div className="flex flex-col gap-3 m-auto items-start p-8 min-w-85 sm:min-w-96 border border-zinc-300 outline-none rounded-xl text-zinc-600 text-sm shadow-lg">
                <p className="text-2xl font-semibold">{state === 'Sign Up' ? "Create Account" : "Login"}</p>
                <p>Please {state === 'Sign Up' ? "sign up" : "log in"} to book appointment</p>
                {
                    state === 'Sign Up' && <div className="w-full">
                        <p>Full Name</p>
                        <input
                            className="border border-zinc-400 rounded w-full p-2 mt-1"
                            type="text"
                            onChange={(e) => setName(e.target.value)}
                            value={name} required
                        />
                    </div>
                }
                <div className="w-full">
                    <p>Email</p>
                    <input
                        className="border border-zinc-400 rounded w-full p-2 mt-1"
                        type="email"
                        onChange={(e) => setEmail(e.target.value)}
                        value={email} required
                    />
                </div>
                <div className="w-full">
                    <p>Password</p>
                    <input
                        className="border border-zinc-400 rounded w-full p-2 mt-1"
                        type="password"
                        onChange={(e) => setPassword(e.target.value)}
                        value={password} required
                    />
                </div>
                <button className="bg-indigo-500 text-slate-50 w-full py-2 rounded-md text-base">
                    {state === 'Sign Up' ? "Create Account" : "Login"}
                </button>
                {
                    state === 'Sign Up'
                        ? <p>Already have an account? <span onClick={() => setState('Login')} className="text-indigo-500 underline cursor-pointer">Login here</span></p> 
                        : <p>Create a new account? <span onClick={() => setState('Sign Up')} className="text-indigo-500 underline cursor-pointer">click here</span></p>
                }
            </div>
        </form>
    )
}

export default Login

// admin/src/pages/Login.vue
<script setup>
import { ref } from 'vue'

const state = ref('Admin')
const email = ref('')
const password = ref('')

const onSubmitHandler = (event) => {
    event.preventDefault()
}
</script>

<template>
    <form
        @submit="onSubmitHandler"
        class="min-h-[80vh] flex items-center"
    >
        <div class="flex flex-col gap-3 m-auto items-start p-8 min-w-85 sm:min-w-96 border rounded-xl text-[#5e5e5e] text-sm shadow-lg">
            <p class="text-2xl font-semibold m-auto">
                <span class="text-indigo-500"> {{ state }} </span> Login
            </p>
            <div class="w-full">
                <p>Email</p>
                <input
                    v-model="email"
                    class="border border-[#dadada] rounded w-full p-2 mt-1"
                    type="email"
                    required
                />
            </div>
            <div class="w-full">
                <p>Password</p>
                <input
                    v-model="password"
                    class="border border-[#dadada] rounded w-full p-2 mt-1"
                    type="password"
                    required
                />
            </div>
            <button class="bg-indigo-500 text-slate-50 w-full py-2 rounded-md text-base">
                Login
            </button>

            <!-- Equivalente al operador ternario de React -->
            <p v-if="state === 'Admin'">
                Doctor Login?
                <span
                    class="text-indigo-500 underline cursor-pointer"
                    @click="state = 'Doctor'"
                >
                    Click here
                </span>
            </p>
            <p v-else>
                Admin Login?
                <span
                    class="text-indigo-500 underline cursor-pointer"
                    @click="state = 'Admin'"
                >
                    Click here
                </span>
            </p>
        </div>
    </form>
</template>
