// frontend/src/components/Navbar.jsx
import { NavLink, useNavigate } from 'react-router-dom'
import { assets } from '../assets/assets'
import { useContext, useState } from 'react';
import { AppContext } from '../context/AppContext';

const Navbar = () => {

    const navigate = useNavigate();
    const { token, setToken } = useContext(AppContext)
    const [showMenu, setShowMenu] = useState(false);

    const logout = () => {
        setToken(false)
        localStorage.removeItem('token')
    }

    return (
        <div className='flex items-center justify-between text-sm py-4 mb-5 border-b border-b-slate-500'>
            <img
                onClick={()=>navigate('/')}
                className='w-44 cursor-pointer' src={assets.logo} alt=""
            />
            <ul className='hidden md:flex items-start gap-5 font-medium'>
                <NavLink to='/'>
                    <li className='py-1'>HOME</li>
                    <hr className='border-none outline-none h-0.5 bg-indigo-700 w-3/5 m-auto hidden' />
                </NavLink>
                <NavLink to='/doctors'>
                    <li className='py-1'>ALL DOCTORS</li>
                    <hr className='border-none outline-none h-0.5 bg-indigo-700 w-3/5 m-auto hidden' />
                </NavLink>
                <NavLink to='/about'>
                    <li className='py-1'>ABOUT</li>
                    <hr className='border-none outline-none h-0.5 bg-indigo-700 w-3/5 m-auto hidden' />
                </NavLink>
                <NavLink to='/contact'>
                    <li className='py-1'>CONTACT</li>
                    <hr className='border-none outline-none h-0.5 bg-indigo-700 w-3/5 m-auto hidden' />
                </NavLink>
            </ul>
            <div className='flex items-center gap-4'>
                {
                    token
                        ? <div className='flex items-center gap-2 cursor-pointer group relative'>
                            <img className='w-8 rounded-full' src={assets.profile_pic} alt="" />
                            <img className='w-2.5' src={assets.dropdown_icon} alt="" />
                            <div className='absolute top-0 right-0 pt-14 text-base font-medium text-slate-500 z-20 hidden group-hover:block'>
                                <div className='min-w-48 bg-stone-100 rounded flex flex-col gap-4 p-4'>
                                    <p
                                        onClick={() => navigate('my-profile')}
                                        className='hover:text-slate-950 cursor-pointer'
                                    >
                                        My Profile
                                    </p>
                                    <p
                                        onClick={() => navigate('my-appointments')}
                                        className='hover:text-slate-950 cursor-pointer'
                                    >
                                        My Appointments
                                    </p>
                                    <p
                                        onClick={logout}
                                        className='hover:text-slate-950 cursor-pointer'
                                    >
                                        Logout
                                    </p>
                                </div>
                            </div>
                        </div>
                        : <button
                            onClick={() => navigate('/login')}
                            className='bg-indigo-600 text-slate-100 px-8 py-3 rounded-full font-medium hidden md:block cursor-pointer'
                        >
                            Create Account
                        </button>
                }
                <img
                    onClick={() => setShowMenu(true)}
                    className='w-6 md:hidden'
                    src={assets.menu_icon}
                    alt=""
                />
                {/* Mobile Menu */}
                <div className={`${showMenu ? 'fixed w-full' : 'h-0 w-0'} md:hidden right-0 top-0 bottom-0 z-20 overflow-hidden bg-indigo-100 transition-all`}>
                    <div className='flex items-center justify-between px-5 py-6'>
                        <img
                            className='w-36'
                            src={assets.logo}
                            alt=""
                        />
                        <img
                            className='w-7'
                            onClick={() => setShowMenu(false)}
                            src={assets.cross_icon}
                            alt=""
                        />
                    </div>
                    <ul className='flex flex-col items-center gap-2 mt-5 px-5 text-lg font-medium'>
                        <NavLink
                            onClick={() => setShowMenu(false)}
                            to='/'
                        >
                            <p className='px-4 py-2 rounded inline-block'>HOME</p>
                        </NavLink>
                        <NavLink
                            onClick={() => setShowMenu(false)}
                            to='/doctors'
                        >
                            <p className='px-4 py-2 rounded inline-block'>ALL DOCTORS</p>
                        </NavLink>
                        <NavLink
                            onClick={() => setShowMenu(false)}
                            to='/about'
                        >
                            <p className='px-4 py-2 rounded inline-block'>ABOUT</p>
                        </NavLink>
                        <NavLink
                            onClick={() => setShowMenu(false)}
                            to='/contact'
                        >
                            <p className='px-4 py-2 rounded inline-block'>CONTACT</p>
                        </NavLink>
                    </ul>
                </div>
            </div>
        </div>
    )
}

export default Navbar

// admin/src/components/Navbar.vue
<script setup>
import { useAdminContext } from '../context/AdminContext';
import { assets } from '../assets/assets';
import { useRouter } from 'vue-router';

const { aToken, setAToken } = useAdminContext()
const router = useRouter()

const logout = () => {
    if (aToken.value) {
        setAToken('')
        localStorage.removeItem('aToken')
        router.push('/')
    }
}
</script>

<template>
    <div class="flex justify-between items-center px-4 sm:px-10 py-3 border-b border-neutral-400 bg-indigo-100">
        <div class="flex items-center gap-2 text-xs">
            <img 
                class="w-36 sm:w-40 cursor-pointer"
                :src="assets.admin_logo" 
                alt=""
            />
            <p class="border px-2.5 py-0.5 rounded-full border-gray-500 text-slate-600">
                {{ aToken ? 'Admin' : 'Doctor' }}
            </p>
        </div>
        <button
            @click="logout"
            class="bg-indigo-500 text-white text-sm px-10 py-2 rounded-full cursor-pointer hover:bg-indigo-600 transition-colors"
        >
            Logout
        </button>
    </div>
</template>
